version: "2"

run:
  timeout: "5m"
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - unused
    - goconst
    - gocritic
    - revive
    - gosec
  settings:
    revive:
      severity: warning
    gosec:
      excludes:
        - G104
        - G306
        - G404
    goconst:
      min-len: 3
      min-occurrences: 3
  exclusions:
    paths:
      - bin
      - vendor

