apiVersion: v1
kind: Namespace
metadata:
  name: cno
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-burner
  namespace: cno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-burner
  template:
    metadata:
      labels:
        app: grpc-burner
    spec:
      containers:
        - name: server
          image: cno/grpc-burner:ci
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 8080
            - name: metrics
              containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-burner
  namespace: cno
spec:
  selector:
    app: grpc-burner
  ports:
    - name: grpc
      port: 8080
      targetPort: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-burner-metrics
  namespace: cno
spec:
  selector:
    app: grpc-burner
  ports:
    - name: http-metrics
      port: 9090
      targetPort: metrics
